# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events, but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
    deploy-qa:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: qa
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo Line added by Moe
          echo Line added by Moe from GitHub
          echo ${{ secrets.MY_FIRST_SECRET }}
          if [  ${{ secrets.MY_FIRST_SECRET }} = "qa_secret" ]; then
            echo "✅ Secret matches expected value"
          else
            echo "❌ Secret does not match"
          fi
    deploy-uat:
    runs-on: ubuntu-latest
    needs: deploy-qa          
    environment: uat
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo Line added by Moe
          echo Line added by Moe from GitHub
          echo ${{ secrets.MY_FIRST_SECRET }}
          if [  ${{ secrets.MY_FIRST_SECRET }} = "uat_secret" ]; then
            echo "✅ Secret matches expected value"
          else
            echo "❌ Secret does not match"
          fi
  deploy-prod:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: deploy-uat
    environment: prod
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo Line added by Moe
          echo Line added by Moe from GitHub
          echo ${{ secrets.MY_FIRST_SECRET }}
          if [  ${{ secrets.MY_FIRST_SECRET }} = "prod_secret" ]; then
            echo "✅ Secret matches expected value"
          else
            echo "❌ Secret does not match"
          fi
